# Generated by Django 5.2.1 on 2025-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
